routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
use Spatie\Activitylog\Models\Activity;

Route::group(['prefix' => '/backoffice', 'as' => 'backoffice.', 'middleware' => ['web', 'auth', 'verified'], 'namespace' => '\App\Http\Controllers\BackOffice'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('/appointments', ['as' => 'appointments', 'uses' => 'AppointmentsController@index']);
    Route::get('/appointments/{appointment}/view', ['as' => 'appointments.view', 'uses' => 'AppointmentsController@show']);
    Route::post('/appointments/{appointment}/approve', ['as' => 'appointments.approve', 'uses' => 'AppointmentsController@approve']);
    Route::post('/appointments/{appointment}/cancel', ['as' => 'appointments.cancel', 'uses' => 'AppointmentsController@cancel']);
    Route::post('/appointments/{appointment}/reminder', ['as' => 'appointments.reminder', 'uses' => 'AppointmentsController@reminder']);
    Route::get('/appointments/{appointment}/update', ['as' => 'appointments.update', 'uses' => 'AppointmentsController@edit']);
    Route::post('/appointments/{appointment}/update', ['as' => 'appointments.save', 'uses' => 'AppointmentsController@save']);

    Route::get('/appointments/create', ['as' => 'appointments.create', 'uses' => 'AppointmentsController@create']);
    Route::post('/appointments/create', ['as' => 'appointments.create_app', 'uses' => 'AppointmentsController@save']);

    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/team/create', ['as' => 'team.create', 'uses' => 'TeamController@create']);
    Route::post('/team/create', ['as' => 'team.store', 'uses' => 'TeamController@store']);
    Route::get('/team/{user}/edit', ['as' => 'team.edit', 'uses' => 'TeamController@edit']);
    Route::post('/team/{user}/edit', ['as' => 'team.update', 'uses' => 'TeamController@update']);

    Route::get('/team/{user}/upload', ['as' => 'team.upload', 'uses' => 'TeamController@upload']);
    Route::post('/team/{user}/phouploadto', ['as' => 'team.upload_photo', 'uses' => 'TeamController@upload_photo']);

    Route::get('/team/{user}/time-plan', ['as' => 'team.time_plan', 'uses' => 'TeamController@time_plan']);
    Route::post('/team/{user}/time-plan', ['as' => 'team.time_plan_update', 'uses' => 'TeamController@time_plan_update']);
    Route::get('/team/{user}/appointments', ['as' => 'team.appointments', 'uses' => 'TeamController@appointments']);

    Route::get('/account', ['as' => 'account', 'uses' => 'AccountController@index'])->middleware('can:admin-access');
    Route::post('/account', ['as' => 'account.update', 'uses' => 'AccountController@update']);

    Route::get('/profile', ['as' => 'profile', 'uses' => 'ProfileController@index']);
    Route::post('/profile', ['as' => 'profile.save', 'uses' => 'ProfileController@save']);

    Route::get('/customize', ['as' => 'customize', 'uses' => 'CustomizeController@index']);
    Route::post('/customize', ['as' => 'account.template.save', 'uses' => 'CustomizeController@template']);
    Route::post('/customize/upload', ['as' => 'account.upload', 'uses' => 'CustomizeController@upload']);
 

    Route::get('/customers', ['as' => 'customers.index', 'uses' => 'CustomersController@index']);
    Route::get('/customers/{customer}/edit', ['as' => 'customers.edit', 'uses' => 'CustomersController@edit']);
    Route::post('/customers/{customer}/edit', ['as' => 'customers.update', 'uses' => 'CustomersController@update']);
    Route::get('customers/{customer}/appointments', ['as' => 'customers.appointments', 'uses' => 'CustomersController@appointments']);

    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServicesController@index']);
    Route::get('/services/create', ['as' => 'services.create', 'uses' => 'ServicesController@create']);
    Route::post('/services/create', ['as' => 'services.store', 'uses' => 'ServicesController@store']);
    Route::get('/services/{service}/edit', ['as' => 'services.edit', 'uses' => 'ServicesController@edit']);
    Route::post('/services/{service}/edit', ['as' => 'services.update', 'uses' => 'ServicesController@update']);
    Route::get('/services/{service}/delete', ['as' => 'services.delete', 'uses' => 'ServicesController@delete']);
    Route::post('/services/{service}/delete', ['as' => 'services.destroy', 'uses' => 'ServicesController@destroy']);
    Route::get('/services/{service}/upload', ['as' => 'services.upload', 'uses' => 'ServicesController@upload']);
    Route::post('/services/{service}/phouploadto', ['as' => 'services.upload_photo', 'uses' => 'ServicesController@upload_photo']);
});

Route::group(['prefix' => '/', 'as' => 'frontoffice.', 'middleware' => ['web'], 'namespace' => '\App\Http\Controllers\FrontOffice'], function () {
    Route::get('/', ['as' => 'home', 'uses' => 'PageController@index']);
    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServiceController@index']);
    Route::get('/team/{userSlug}', ['as' => 'team.member.view', 'uses' => 'TeamController@member_view']);
    Route::get('/services/{serviceSlug}', ['as' => 'service.view', 'uses' => 'ServiceController@show']);
    Route::get('/book/{userSlug}/{serviceSlug}', ['as' => 'book.create', 'uses' => 'BookController@index']);
});

Auth::routes(['verify' => true]);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Customer;
use App\Models\Service;
use App\Models\TimePlan;
use App\Models\User;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;
    
    protected $fillable = ['name', 'package_id', 'token', 'status', 'email'];

    public function getAddressInfoAttribute()
    {
        $text = null;
        if ($this->address) {
            $text .= $this->address . ' ';
        }

        if ($this->city_name) {
            $text .= $this->city_name . ' ';
        }

        if ($this->postcode) {
            $text .= $this->postcode . ' ';
        }
        return $text;
    }

    public function getTemplateFileNameAttribute()
    {
        if (isset($this->template)) {
            return $this->template->file_name;
        }
        return "default";
    }

    public function getLastOrderAttribute()
    {
        $order = $this->orders->last();
        if ($order) {
            return $order;
        }
        return;
    }

    public function customers()
    {
        return $this->hasMany(Customer::class);
    }

    public function services()
    {
        return $this->hasMany(Service::class);
    }

    public function team()
    {
        return $this->hasMany(User::class)->whereHas('roles', function ($query) {
            $query->whereIn('name', ['team_member', 'owner']);
        });
    }

    public function owner_name()
    {
        if ($this->owner){
            return $this->owner->name;
        }
        return;
    }

    public function owner()
    {
        return $this->hasMany(User::class)->whereHas('roles', function ($query) {
            $query->where('name', 'owner');
        });
    }

    public function getOwnerNameAttribute()
    {
        if (isset($this->owner->first()->name)) {
            return $this->owner->first()->name;
        }
        return "";
    }

    public function getOwnerEmailAttribute()
    {
        if (isset($this->owner->first()->email)) {
            return $this->owner->first()->email;
        }
        return "";
    }

    public function getCompanyEmailAttribute()
    {
        if (empty($this->email)) {
            return $this->owner->first()->email;
        }
        return $this->email;
    }


    public function users()
    {
        return $this->hasMany(User::class);
    }
 
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function reports()
    {
        return $this->hasMany(Report::class);
    }

    public function template()
    {
        return $this->belongsTo(Template::class);
    }
 
    public function appointments()
    {
        return $this->hasMany(Appointment::class);
    }

    public function getCountryNameAttribute()
    {
        if ($this->country) {
            return Country::find($this->country)->name;
        }
        return;
    }

    public function getCityNameAttribute()
    {
        if ($this->city) {
            return City::find($this->city)->name;
        }
        return;
    }

    public function getStateNameAttribute()
    {
        if ($this->state) {
            return Division::find($this->state)->name;
        }
        return;
    }

    public function getAddressBoxAttribute()
    {
        $address = $this->address . "<br/>" . $this->postcode . "<br/>" . $this->city_name . " " . $this->city_name . " " . $this->country_name;
        return $address;
    }
/*
public static function boot()
{
parent::boot();

static::saving(function ($model) {
$model->slug = str_slug($model->name);
});

}

public function getRouteKeyName()
{
return 'slug';
} */
}

resources/views/frontoffice/basic/partials/company.blade.php
<header>
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ $company->name }}</h1>
        <p class="">{!! $company->description !!}</p>
        <p class="lead">{{ $company->address_info }} <br/>
        @if($company->phone)
        Phone:{{ $company->phone }}
        @endif
        </p>
    </div>
</header>

resources/views/frontoffice/basic/partials/header.blade.php
<header>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a
                href="{{ route('frontoffice.home') }}">{{ $company->name }}</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">
        @if ($company->team->count() > 1)
            <a class="p-2 text-dark" href="{{ route('frontoffice.team.index') }}">Team</a>
            @endif
            <a class="p-2 text-dark" href="{{ route('frontoffice.services.index') }}">Services</a>
        </nav>
    </div>
</header>

resources/views/frontoffice/basic/partials/services.blade.php
@if ($company->services->count() > 0)

@if ($company->services->count() == 1)
@php
$service = $company->services->first();
@endphp


<section class="ilitems padding-lg">
    <ul class="row">
        <li class="col-12 col-md-12 col-lg-12">
            <div class="cnt-block" style="height: 389px;">
                <h3><a
                        href="{{ route('frontoffice.service.view', [$service->slug]) }}">{{ $service->name }}</a>
                </h3>

                @if ($service->image)
                <a href="{{ route('frontoffice.service.view', [$service->slug]) }}">
                    <img src="{{ Storage::url('uploads/services/thump_'.$service->image )  }}"
                        class="img-fluid m-2" /></a>
                @else
                <a href="{{ route('frontoffice.service.view', [$service->slug]) }}">
                    <img src="{{ asset('images/not-available.png')}}" class="img-fluid m-2" /></a>


                @endif
                <p>{{ $service->duration }} minutes</p>
                @if ($service->price > 0)
                <p>costs £{{ $service->price }}</p>
                @endif
                @if(isset($user->slug) && isset($service->slug))
                <a class="btn btn-sm btn-info btn-block"
                    href="{{ route('frontoffice.book.create', [$user->slug, $service->slug]) }}">Book
                    Now</a>
                @endif
            </div>
        </li>
    </ul>
</section>

@else
<section class="ilitems padding-lg">
    <h3>Services:</h3>
    <ul class="row">
        @foreach($company->services as $service)
        <li class="col-12 col-md-6 col-lg-4">
            <div class="cnt-block" style="height: 389px;">
                <h3><a
                        href="{{ route('frontoffice.service.view', [$service->slug]) }}">{{ $service->name }}</a>
                </h3>

                @if ($service->image)
                <a href="{{ route('frontoffice.service.view', [$service->slug]) }}">
                    <img src="{{ Storage::url('uploads/services/thump_'.$service->image )  }}"
                        class="img-fluid m-2" /></a>
                @else
                <a href="{{ route('frontoffice.service.view', [$service->slug]) }}">
                    <img src="{{ asset('images/not-available.png')}}" class="img-fluid m-2" /></a>


                @endif
                <p>{{ $service->duration }} minutes</p>
                @if ($service->price > 0)
                <p>costs £{{ $service->price }}</p>
                @endif
                @if(isset($user->slug) && isset($service->slug))
                <a class="btn btn-md btn-info btn-block"
                    href="{{ route('frontoffice.book.create', [$user->slug, $service->slug]) }}">Book
                    Now</a>
                @endif
            </div>
        </li>
        @endforeach
    </ul>
</section>
@endif
@endif

resources/views/frontoffice/basic/partials/team.blade.php
@if ($company->team->count() > 1)
<section class="ilitems padding-lg">
    <h3>Team:</h3>
    <ul class="row">
        @foreach($company->team as $user)

        @if ($user->services()->count() > 0)
        <li class="col-12 col-md-6 col-lg-4">
            <div class="cnt-block" style="height: 349px;">
                <h3><a
                        href="{{ route('frontoffice.team.member.view', [  $user->slug]) }}">{{ $user->name }}</a>
                </h3>
                @if(isset($user->slug) && isset($service->slug))
                <a href="{{ route('frontoffice.book.create', [ $user->slug, $service->slug]) }}">
                    @if($user->image)
                    <img src="{{ Storage::url('uploads/users/thump_'.$user->image)  }}" class="img-fluid m-2" />
                    @else
                    <img src="{{ asset('images/not-available.png')}}" class="img-fluid m-2" />
                    @endif
                </a>

                <a class="btn btn-lg btn-info btn-block"
                    href="{{ route('frontoffice.book.create', [ $user->slug, $service->slug]) }}">Book
                    Now</a>
                @else
                <a href="{{ route('frontoffice.team.member.view', [  $user->slug]) }}">
                    @if($user->image)
                    <img src="{{ Storage::url('uploads/users/thump_'.$user->image)  }}" class="img-fluid m-2" />
                    @else
                    <img src="{{ asset('images/not-available.png')}}" class="img-fluid m-2" />
                    @endif
                    @endif
            </div>
        </li>
        @endif
        @endforeach
    </ul>
</section>
@endif