routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
use Spatie\Activitylog\Models\Activity;

Route::group(['prefix' => '/backoffice', 'as' => 'backoffice.', 'middleware' => ['web', 'auth', 'verified'], 'namespace' => '\App\Http\Controllers\BackOffice'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('/appointments', ['as' => 'appointments', 'uses' => 'AppointmentsController@index']);
    Route::get('/appointments/{appointment}/view', ['as' => 'appointments.view', 'uses' => 'AppointmentsController@show']);
    Route::post('/appointments/{appointment}/approve', ['as' => 'appointments.approve', 'uses' => 'AppointmentsController@approve']);
    Route::post('/appointments/{appointment}/cancel', ['as' => 'appointments.cancel', 'uses' => 'AppointmentsController@cancel']);
    Route::post('/appointments/{appointment}/reminder', ['as' => 'appointments.reminder', 'uses' => 'AppointmentsController@reminder']);
    Route::get('/appointments/{appointment}/update', ['as' => 'appointments.update', 'uses' => 'AppointmentsController@edit']);
    Route::post('/appointments/{appointment}/update', ['as' => 'appointments.save', 'uses' => 'AppointmentsController@save']);

    Route::get('/appointments/create', ['as' => 'appointments.create', 'uses' => 'AppointmentsController@create']);
    Route::post('/appointments/create', ['as' => 'appointments.create_app', 'uses' => 'AppointmentsController@save']);

    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/team/create', ['as' => 'team.create', 'uses' => 'TeamController@create']);
    Route::post('/team/create', ['as' => 'team.store', 'uses' => 'TeamController@store']);
    Route::get('/team/{user}/edit', ['as' => 'team.edit', 'uses' => 'TeamController@edit']);
    Route::post('/team/{user}/edit', ['as' => 'team.update', 'uses' => 'TeamController@update']);

    Route::get('/team/{user}/upload', ['as' => 'team.upload', 'uses' => 'TeamController@upload']);
    Route::post('/team/{user}/phouploadto', ['as' => 'team.upload_photo', 'uses' => 'TeamController@upload_photo']);

    Route::get('/team/{user}/time-plan', ['as' => 'team.time_plan', 'uses' => 'TeamController@time_plan']);
    Route::post('/team/{user}/time-plan', ['as' => 'team.time_plan_update', 'uses' => 'TeamController@time_plan_update']);
    Route::get('/team/{user}/appointments', ['as' => 'team.appointments', 'uses' => 'TeamController@appointments']);

    Route::get('/account', ['as' => 'account', 'uses' => 'AccountController@index'])->middleware('can:admin-access');
    Route::post('/account', ['as' => 'account.update', 'uses' => 'AccountController@update']);

    Route::get('/profile', ['as' => 'profile', 'uses' => 'ProfileController@index']);
    Route::post('/profile', ['as' => 'profile.save', 'uses' => 'ProfileController@save']);

    Route::get('/customize', ['as' => 'customize', 'uses' => 'CustomizeController@index']);
    Route::post('/customize', ['as' => 'account.template.save', 'uses' => 'CustomizeController@template']);
    Route::post('/customize/upload', ['as' => 'account.upload', 'uses' => 'CustomizeController@upload']);
 

    Route::get('/customers', ['as' => 'customers.index', 'uses' => 'CustomersController@index']);
    Route::get('/customers/{customer}/edit', ['as' => 'customers.edit', 'uses' => 'CustomersController@edit']);
    Route::post('/customers/{customer}/edit', ['as' => 'customers.update', 'uses' => 'CustomersController@update']);
    Route::get('customers/{customer}/appointments', ['as' => 'customers.appointments', 'uses' => 'CustomersController@appointments']);

    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServicesController@index']);
    Route::get('/services/create', ['as' => 'services.create', 'uses' => 'ServicesController@create']);
    Route::post('/services/create', ['as' => 'services.store', 'uses' => 'ServicesController@store']);
    Route::get('/services/{service}/edit', ['as' => 'services.edit', 'uses' => 'ServicesController@edit']);
    Route::post('/services/{service}/edit', ['as' => 'services.update', 'uses' => 'ServicesController@update']);
    Route::get('/services/{service}/delete', ['as' => 'services.delete', 'uses' => 'ServicesController@delete']);
    Route::post('/services/{service}/delete', ['as' => 'services.destroy', 'uses' => 'ServicesController@destroy']);
    Route::get('/services/{service}/upload', ['as' => 'services.upload', 'uses' => 'ServicesController@upload']);
    Route::post('/services/{service}/phouploadto', ['as' => 'services.upload_photo', 'uses' => 'ServicesController@upload_photo']);
});

Route::group(['prefix' => '/', 'as' => 'frontoffice.', 'middleware' => ['web'], 'namespace' => '\App\Http\Controllers\FrontOffice'], function () {
    Route::get('/', ['as' => 'home', 'uses' => 'PageController@index']);
    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServiceController@index']);
    Route::get('/team/{userSlug}', ['as' => 'team.member.view', 'uses' => 'TeamController@member_view']);
    Route::get('/services/{serviceSlug}', ['as' => 'service.view', 'uses' => 'ServiceController@show']);
    Route::get('/book/{userSlug}/{serviceSlug}', ['as' => 'book.create', 'uses' => 'BookController@index']);
});

Auth::routes(['verify' => true]);

app/Models/Appointment.php
<?php
 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;
use App\Helper;

class Appointment extends Model
{
    use SoftDeletes;

    protected $dates = ['start_time', 'end_time'];

    public function history()
    {
        return $this->hasMany(AppointmentHistory::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function service()
    {
        return $this->belongsTo(Service::class)->withTrashed();
    }

    public function staff()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
	
    public function customer()
    {
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }	

    public function getAppointmentTimeAttribute()
    {
        $start_time = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->start_time);
        $end_time = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->end_time);
        return $start_time->format('H:i') . " - " . $end_time->format('H:i') . "<br/><i>" . $start_time->toFormattedDateString() . "</i>";
    }

    public function getAppointmentTimeUserAttribute()
    {
        $timezone = Auth::user()->timezone;
        $date = Helper::convert($this->start_time, $timezone, 'UTC', 'd M Y');
        $start_time = Helper::convert($this->start_time, $timezone, 'UTC', 'H:i');
        $end_time = Helper::convert($this->end_time, $timezone, 'UTC', 'H:i');
        return  $start_time . ' - ' . $end_time  . '<br/>'.  $date ."</i>";
    }    

    public function getIsApprovedStyleAttribute()
    {
        if ($this->approved) {
            return "text-success";
        }
        return "text-warning";
    }

    public function getIsApprovedAttribute()
    {
        if ($this->approved) {
            return "Approved";
        }
        return "Pending";
    }

    public function getStatusMessageAttribute()
    {
        if ($this->status) {
            return "Estimated";
        }
        return "Canceled";
    }    
}

app/Http/Controllers/BackOffice/AccountController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Http\Requests\AccountRequest;
use App\Models\Company;
use App\Models\Template;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Intervention\Image\Facades\Image;
use Khsing\World\Models\City;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Auth::user()->company;
        $templates = [];
        $templates['basic'] = 'Basic';
        return view('backoffice.account.index', compact('company', 'templates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AccountRequest $request)
    {
        $company = Auth::user()->company;
        $company->name = $request->name;
        $company->description = $request->description;
        $company->address = $request->address;
        $company->postcode = $request->postcode;
        $company->email = $request->email;
        $company->phone = $request->phone;
        $company->website = $request->website;
        $company->auto_renew = $request->auto_renew;
        $company->template_name = $request->template;
        if ($company->save()) {
            return redirect(route('backoffice.account'))->with('success', trans('Your account has been updated'));
        }
        $error = $company->errors()->all(':message');
        return redirect(route('backoffice.account'))->with('error', $error)->withInput();
    }

    public function orders()
    {
        $company = Auth::user()->company;
        return view('backoffice.account.orders', compact('company'));
    }

    public function template_save(Request $request)
    {
        $company = Auth::user()->company;
        $company->template_id = $request->template_id;
        $company->save();
        return redirect(route('backoffice.account.customize'))->with('success', trans('Your template has been updated'));
    }

    public function customize()
    {
        $company = Auth::user()->company;
        $templateDatas = Template::all();

        $templates[0] = " - - - - - ";
        foreach ($templateDatas as $data) {
            $templates[$data->id] = $data->name;
        }

        return view('backoffice.account.customize', compact('company', 'templates'));
    }

    public function template(Request $request)
    {
        $company = Auth::user()->company;
        $company->template = $request->template;
        if ($company->save()) {
            return redirect(route('backoffice.account.customize'))->with('success', trans('Your account has been updated'));
        }
    }

    public function upload(Request $request)
    {
        $user = Auth::user();
        $company = $user->company;
        $file = $request->croppedImage;
        $img = Image::make($file);

        $types = ['image/jpeg' => 'jpg', 'image/jpg' => 'jpg', 'image/png' => 'png', '	image/gif' => 'gif'];
        $type = (isset($types[$img->mime()])) ? $types[$img->mime()] : 'jpg';
        $image_name = time() . "." . $type;
        \Storage::disk('local')->put('public/company/images/' . $company->id . '/' . (string) $image_name, $img->encode(), 'public');

        $company->logo = $image_name;
        if ($company->save()) {
            return asset('storage/company/images/' . $company->id . '/' . $image_name);
        }
        return "There are some problems with your submission!";
    }
}

app/Http/Controllers/BackOffice/BaseController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Models\User;
use Auth;
use Illuminate\Routing\Controller;

class BaseController extends Controller
{
    public function __construct()
    {
 
    }
}

app/Http/Controllers/BackOffice/CustomersController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Models\Customer;
use Illuminate\Http\Request;
use Khsing\World\Models\City;
use Khsing\World\Models\Country;
use Illuminate\Routing\Controller;
use Auth;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company_id = Auth::user()->company->id;
        $customers = Customer::whereHas('appointments', function ($query) use ($company_id) {
            $query->where("company_id", $company_id);
        })->get();

        return view('backoffice.customers.index', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cityData = City::where('country_id', 148)->get();

        $cities[0] = " - - - - - ";
        foreach ($cityData as $city) {
            $cities[$city->id] = $city->name;
        }

        return view('backoffice::customers.create_edit', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $customer = new Customer;
        $customer->name = $request->name;
        $customer->email = $request->email;
        $customer->phone = $request->phone;
        $customer->address = $request->address;
        $customer->city = $request->city;
        $customer->state = $request->state;
        $customer->postcode = $request->postcode;
        $customer->country = $request->country;
        $customer->timezone = $request->timezone;
        $customer->language = $request->language;

        if ($customer->save()) {
            return redirect(route('backoffice.customers.edit', $customer->id))->with('success', trans('labels.form.success'));
        }
        $error = $customer->errors()->all(':message');
        return redirect(route('backoffice.customers.create'))->with('error', $error)->withInput();
    }
 

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        $cityData = City::where('country_id', 148)->get();
        $cities[0] = " - - - - - ";
        foreach ($cityData as $city) {
            $cities[$city->id] = $city->name;
        }
        return view('backoffice::customers.create_edit', compact('customer', 'cities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $customer->name = $request->name;
        $customer->email = $request->email;
        $customer->phone = $request->phone;
        $customer->address = $request->address;
        $customer->city = (!empty($request->city) ? $request->city : $customer->city);
        $customer->state = (!empty($request->state) ? $request->state : $customer->state);
        $customer->postcode = $request->postcode;
        $customer->country = $request->country;
        $customer->timezone = $request->timezone;
        $customer->language = $request->language;
        $customer->company_id = Auth::user()->company->id;
        if ($customer->save()) {
            return redirect(route('backoffice.customers.edit', $customer->id))->with('success', trans('labels.form.success'));
        }
        $error = $customer->errors()->all(':message');
        return redirect(route('backoffice.customers.create'))->with('error', $error)->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function appointments(Customer $customer){
        $company_id = Auth::user()->company->id;
        $appointments = $customer->appointments()->where("company_id", $company_id)->get();
        return view('backoffice::customers.appointments', compact('customer', 'appointments'));
    }
}

app/Http/Controllers/BackOffice/ProfileController.php
<?php

namespace App\Http\Controllers\BackOffice;

use Auth;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use App\Http\Requests\ProfileRequest;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        return view('backoffice.profile', compact('user'));
    }

    public function save(ProfileRequest $request)
    {
        $user = Auth::user();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        activity()
        ->causedBy($user)
        ->log($user->name . 'Updated the profile');    

        return redirect(route('backoffice.profile'))->with('success', trans('Your profile has been updated!'));
    }
}

app/Http/Controllers/FrontOffice/TeamController.php
<?php

namespace App\Http\Controllers\FrontOffice;

use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Models\Company;
use App\Models\Service;
use App\Models\User;

class TeamController extends BaseController
{
    public function __construct()
    {
        parent::__construct();
    }
    
    public function index()
    {
        $company = $this->company;
        return view("frontoffice.{$company->template_name}.team", compact('company'));
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function member_view(User $user)
    {
        $company = $this->company;
        return view("frontoffice.{$company->template_name}.user_view", compact('company', 'user'));
    }
}

resources/views/backoffice/team/appointments.blade.php
@extends('layouts.panel')
@section('title')
Scheduled Appointments of {{ $user->name }}
@parent
@stop

@section('content')


<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="card-title float-left"> Scheduled Appointments of {{ $user->name }}</h4>
                        </div>
                        <div class="col-md-2 float-right">
                            <a class="btn btn-sm btn-primary float-right" href="{{ route('backoffice.team.index') }}">
                                <i class="align-middle feather_small" data-feather="list"></i>
                                List Staff</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if($appointments->count() > 0)
                    <div class="table-responsive-sm">
                        <table class="table">
                            <thead class="thead-header">
                                <tr>
                                    <th>Appointment At</th>
                                    <th>Service</th>
                                    <th>Staff</th>
                                    <th>Customer Name</th>
                                    <th>Customer Email</th>
                                    <th>Customer Phone</th>
                                    <th>Verified</th>
                                    <th>Created At</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($appointments as $app)
                                <tr>
                                    <td>{!! $app->appointment_time !!}</td>
                                    <td>{{ $app->service->name }}</td>
                                    <td>{{ $app->staff->name }}</td>
                                    <td>{{ $app->customer_name }}</td>
                                    <td>{{ $app->customer_email }}</td>
                                    <td>{{ $app->customer_phone }}</td>
                                    <td>{{ $app->is_verified  }}</td>
                                    <td>{{ Carbon\Carbon::parse($app->created_at)->format('d M Y H:i') }}</td>
                                    <td><a class="btn btn-sm btn-primary"
                                            href="{{ route('backoffice.appointments.view', $app->id) }}">
                                            <i class="align-middle feather_small" data-feather="eye"></i>
                                            {{ trans('labels.view') }}</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $appointments->render() }}
                    @else
                    <div class="alert alert-warning">Sorry, no appointments for {{ $user->name }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')


@stop

resources/views/backoffice/team/create_edit.blade.php
@extends('layouts.panel')
@section('title')
User Management
@parent
@stop
@section('css')
<link href="{{ mix('css/summernote-lite.css') }}" rel="stylesheet">
@stop
@section('content')

<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header container-fluid">
                    <div class="row">
                        <div class="col-md-10">
                            <strong>
                                @if(isset($user))
                                Update user
                                @else
                                Create user
                                @endif
                            </strong>
                        </div>
                        <div class="col-md-2 float-right">
                            <a class="btn btn-sm btn-primary float-right" href="{{ route('backoffice.team.index') }}">
                                <i class="align-middle feather_small" data-feather="list"></i>
                                List Users</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include('backoffice.partials.notifications')
                    <div class="row">
                        <div class="col-sm-10 offset-sm-1">
                            <form autocomplete="off" role="form"
                                action="{{ (isset($user)) ? route('backoffice.team.update', $user->id ) : route('backoffice.team.store') }}"
                                method="POST">
                                <input type="hidden" name="_token" value="{{{ csrf_token() }}}" />

                                <div class="form-group row {!! $errors->first('name', 'has-warning') !!}">
                                    <label for="name" class="col-sm-4 col-form-label">{{ trans('labels.name') }}
                                        </label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" id="name" name="name" autocomplete="off"
                                            value="{{{ old('name', isset($user) ? $user->name : null) }}}">
                                        {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('timezones', 'has-warning') !!}">
                                    <label for="timezone" class="col-sm-4 col-form-label">Timezone</label>
                                    <div class="col-sm-8">
                                        {{ Form::select('timezone', $timezones, (isset($user) ? $user->timezone : $selected), ['class'=>'form-control col-sm-3']) }}
                                        {!! $errors->first('timezone', '<span class="help-inline">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('email', 'has-warning') !!}">
                                    <label for="email" class="col-sm-4 col-form-label">{{ trans('labels.email') }}
                                        </label>
                                    <div class="col-sm-8"><input type="text" class="form-control" id="email"
                                            name="email" autocomplete="off"
                                            value="{{{ old('email', isset($user) ? $user->email : null) }}}">
                                        {!! $errors->first('email', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('description', 'has-warning') !!}">
                                    <label for="description"
                                        class="col-sm-4 col-form-label">{{ trans('labels.description') }}
                                       </label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" id="description"
                                            name="description">{{{ old('description', isset($user) ? $user->description : null) }}}</textarea>
                                        {!! $errors->first('descripton', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('password', 'has-warning') !!}">
                                    <label for="password"
                                        class="col-sm-4 col-form-label">{{ trans('labels.password') }}</label>
                                    <div class="col-sm-8">
                                        <input type="password" class="form-control" id="password" name="password" />
                                        {!! $errors->first('password', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div
                                    class="form-group row {!! $errors->first('password_confirmation', 'has-warning') !!}">
                                    <label for="password_confirmation"
                                        class="col-sm-4 col-form-label">{{ trans('labels.password_confirmation') }}</label>
                                    <div class="col-sm-8">
                                        <input type="password" class="form-control" id="password_confirmation"
                                            name="password_confirmation" />
                                        {!! $errors->first('password_confirmation', '<span
                                            class="help-block">:message</span>') !!}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary pull-right">
                                    <i class="fa fa-save" aria-hidden="true"></i>
                                    {{ trans('labels.save') }}</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('scripts')
<script src="{{ mix('js/summernote-lite.min.js') }}"></script>

<script>
$(document).ready(function() {
    $('#description').summernote({
        height: 100,
        toolbar: false,
        tabsize: 2
    });
});
</script>
@stop

resources/views/backoffice/team/index.blade.php
@extends('layouts.panel')
@section('title')
Users
@parent
@stop

@section('content')

<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header container-fluid">
                    <div class="row">
                        <div class="col-md-10">
                            <strong>
                                @if(isset($user))
                                Modify User
                                @else
                                Create User
                                @endif
                            </strong>
                        </div>
                        <div class="col-md-2 float-right">
                            <a class="btn btn-sm btn-primary float-right" href="{{ route('backoffice.team.create') }}">
                                <i class="align-middle feather_small" data-feather="list"></i>
                                Create User</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">

                    @if($employees->count() < 1) <div class="alert alert-danger mt-4">
                        Sorry, you do not have any employee
                </div>
                @else
                <div class="table-responsive-sm">
                    <table class="table">
                        <thead class="thead-header">
                            <tr>
                                <th>Name / Email</th>
                                <th class="text-right"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($employees as $employee)
                            <tr>
                                <td>{{ $employee->name }}<br />
                                   <i> {{ $employee->email }}</i>
                                </td>
                                <td class="text-right">
                                    <a class="btn btn-sm btn-primary"
                                        href="{{ route('backoffice.team.upload', $employee->id) }}">
                                        <i class="fas fa-upload"></i> Upload</a>

                                    <a class="btn btn-sm btn-primary"
                                        href="{{ route('backoffice.team.time_plan', $employee->id) }}">
                                        <i class="far fa-clock"></i> Time Plan</a>
                                    <a class="btn btn-sm btn-primary"
                                        href="{{ route('backoffice.team.edit', $employee->id) }}">
                                        <i class="align-middle feather_small" data-feather="edit"></i> Edit</a>
                                    <a class="btn btn-sm btn-primary"
                                        href="{{ route('backoffice.team.appointments', $employee->id) }}">
                                        <i class="align-middle feather_small" data-feather="book"></i>
                                        Appointments</a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>

                @endif
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')


@stop