routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
use Spatie\Activitylog\Models\Activity;

Route::group(['prefix' => '/backoffice', 'as' => 'backoffice.', 'middleware' => ['web', 'auth', 'verified'], 'namespace' => '\App\Http\Controllers\BackOffice'], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('/appointments', ['as' => 'appointments', 'uses' => 'AppointmentsController@index']);
    Route::get('/appointments/{appointment}/view', ['as' => 'appointments.view', 'uses' => 'AppointmentsController@show']);
    Route::post('/appointments/{appointment}/approve', ['as' => 'appointments.approve', 'uses' => 'AppointmentsController@approve']);
    Route::post('/appointments/{appointment}/cancel', ['as' => 'appointments.cancel', 'uses' => 'AppointmentsController@cancel']);
    Route::post('/appointments/{appointment}/reminder', ['as' => 'appointments.reminder', 'uses' => 'AppointmentsController@reminder']);
    Route::get('/appointments/{appointment}/update', ['as' => 'appointments.update', 'uses' => 'AppointmentsController@edit']);
    Route::post('/appointments/{appointment}/update', ['as' => 'appointments.save', 'uses' => 'AppointmentsController@save']);

    Route::get('/appointments/create', ['as' => 'appointments.create', 'uses' => 'AppointmentsController@create']);
    Route::post('/appointments/create', ['as' => 'appointments.create_app', 'uses' => 'AppointmentsController@save']);

    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/team/create', ['as' => 'team.create', 'uses' => 'TeamController@create']);
    Route::post('/team/create', ['as' => 'team.store', 'uses' => 'TeamController@store']);
    Route::get('/team/{user}/edit', ['as' => 'team.edit', 'uses' => 'TeamController@edit']);
    Route::post('/team/{user}/edit', ['as' => 'team.update', 'uses' => 'TeamController@update']);

    Route::get('/team/{user}/upload', ['as' => 'team.upload', 'uses' => 'TeamController@upload']);
    Route::post('/team/{user}/phouploadto', ['as' => 'team.upload_photo', 'uses' => 'TeamController@upload_photo']);

    Route::get('/team/{user}/time-plan', ['as' => 'team.time_plan', 'uses' => 'TeamController@time_plan']);
    Route::post('/team/{user}/time-plan', ['as' => 'team.time_plan_update', 'uses' => 'TeamController@time_plan_update']);
    Route::get('/team/{user}/appointments', ['as' => 'team.appointments', 'uses' => 'TeamController@appointments']);

    Route::get('/account', ['as' => 'account', 'uses' => 'AccountController@index'])->middleware('can:admin-access');
    Route::post('/account', ['as' => 'account.update', 'uses' => 'AccountController@update']);

    Route::get('/profile', ['as' => 'profile', 'uses' => 'ProfileController@index']);
    Route::post('/profile', ['as' => 'profile.save', 'uses' => 'ProfileController@save']);

    Route::get('/customize', ['as' => 'customize', 'uses' => 'CustomizeController@index']);
    Route::post('/customize', ['as' => 'account.template.save', 'uses' => 'CustomizeController@template']);
    Route::post('/customize/upload', ['as' => 'account.upload', 'uses' => 'CustomizeController@upload']);
 

    Route::get('/customers', ['as' => 'customers.index', 'uses' => 'CustomersController@index']);
    Route::get('/customers/{customer}/edit', ['as' => 'customers.edit', 'uses' => 'CustomersController@edit']);
    Route::post('/customers/{customer}/edit', ['as' => 'customers.update', 'uses' => 'CustomersController@update']);
    Route::get('customers/{customer}/appointments', ['as' => 'customers.appointments', 'uses' => 'CustomersController@appointments']);

    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServicesController@index']);
    Route::get('/services/create', ['as' => 'services.create', 'uses' => 'ServicesController@create']);
    Route::post('/services/create', ['as' => 'services.store', 'uses' => 'ServicesController@store']);
    Route::get('/services/{service}/edit', ['as' => 'services.edit', 'uses' => 'ServicesController@edit']);
    Route::post('/services/{service}/edit', ['as' => 'services.update', 'uses' => 'ServicesController@update']);
    Route::get('/services/{service}/delete', ['as' => 'services.delete', 'uses' => 'ServicesController@delete']);
    Route::post('/services/{service}/delete', ['as' => 'services.destroy', 'uses' => 'ServicesController@destroy']);
    Route::get('/services/{service}/upload', ['as' => 'services.upload', 'uses' => 'ServicesController@upload']);
    Route::post('/services/{service}/phouploadto', ['as' => 'services.upload_photo', 'uses' => 'ServicesController@upload_photo']);
});

Route::group(['prefix' => '/', 'as' => 'frontoffice.', 'middleware' => ['web'], 'namespace' => '\App\Http\Controllers\FrontOffice'], function () {
    Route::get('/', ['as' => 'home', 'uses' => 'PageController@index']);
    Route::get('/team', ['as' => 'team.index', 'uses' => 'TeamController@index']);
    Route::get('/services', ['as' => 'services.index', 'uses' => 'ServiceController@index']);
    Route::get('/team/{userSlug}', ['as' => 'team.member.view', 'uses' => 'TeamController@member_view']);
    Route::get('/services/{serviceSlug}', ['as' => 'service.view', 'uses' => 'ServiceController@show']);
    Route::get('/book/{userSlug}/{serviceSlug}', ['as' => 'book.create', 'uses' => 'BookController@index']);
});

Auth::routes(['verify' => true]);

app/Models/Service.php
<?php
 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Service extends Model
{
    use SoftDeletes;
    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function team()
    {
        return $this->belongsToMany(User::class, 'service_team')
                ->withPivot(['user_id', 'service_id'])
                ->withTimestamps();
    }

    public function appointments()
    {
        return $this->hasMany(Appointment::class);
    }

    public function getServicePriceAttribute()
    {
        setlocale(LC_MONETARY, 'en_GB');
        return money_format("%i", $this->price);
    }
}

app/Http/Controllers/BackOffice/AccountController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Http\Requests\AccountRequest;
use App\Models\Company;
use App\Models\Template;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Intervention\Image\Facades\Image;
use Khsing\World\Models\City;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Auth::user()->company;
        $templates = [];
        $templates['basic'] = 'Basic';
        return view('backoffice.account.index', compact('company', 'templates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AccountRequest $request)
    {
        $company = Auth::user()->company;
        $company->name = $request->name;
        $company->description = $request->description;
        $company->address = $request->address;
        $company->postcode = $request->postcode;
        $company->email = $request->email;
        $company->phone = $request->phone;
        $company->website = $request->website;
        $company->auto_renew = $request->auto_renew;
        $company->template_name = $request->template;
        if ($company->save()) {
            return redirect(route('backoffice.account'))->with('success', trans('Your account has been updated'));
        }
        $error = $company->errors()->all(':message');
        return redirect(route('backoffice.account'))->with('error', $error)->withInput();
    }

    public function orders()
    {
        $company = Auth::user()->company;
        return view('backoffice.account.orders', compact('company'));
    }

    public function template_save(Request $request)
    {
        $company = Auth::user()->company;
        $company->template_id = $request->template_id;
        $company->save();
        return redirect(route('backoffice.account.customize'))->with('success', trans('Your template has been updated'));
    }

    public function customize()
    {
        $company = Auth::user()->company;
        $templateDatas = Template::all();

        $templates[0] = " - - - - - ";
        foreach ($templateDatas as $data) {
            $templates[$data->id] = $data->name;
        }

        return view('backoffice.account.customize', compact('company', 'templates'));
    }

    public function template(Request $request)
    {
        $company = Auth::user()->company;
        $company->template = $request->template;
        if ($company->save()) {
            return redirect(route('backoffice.account.customize'))->with('success', trans('Your account has been updated'));
        }
    }

    public function upload(Request $request)
    {
        $user = Auth::user();
        $company = $user->company;
        $file = $request->croppedImage;
        $img = Image::make($file);

        $types = ['image/jpeg' => 'jpg', 'image/jpg' => 'jpg', 'image/png' => 'png', '	image/gif' => 'gif'];
        $type = (isset($types[$img->mime()])) ? $types[$img->mime()] : 'jpg';
        $image_name = time() . "." . $type;
        \Storage::disk('local')->put('public/company/images/' . $company->id . '/' . (string) $image_name, $img->encode(), 'public');

        $company->logo = $image_name;
        if ($company->save()) {
            return asset('storage/company/images/' . $company->id . '/' . $image_name);
        }
        return "There are some problems with your submission!";
    }
}

app/Http/Controllers/BackOffice/AppointmentsController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Models\Appointment;
use Illuminate\Http\Request;
use App\Mail\AppointmentApproved; 
use App\Mail\AppointmentReminder;
use App\Mail\AppointmentCanceled;
use Mail;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;
use Auth;
use Spatie\Activitylog\Models\Activity;

class AppointmentsController extends Controller
{
    public function __construct()
    {
 
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        $time = (isset($request->time) ? $request->time : '');
        $approved = (isset($request->approved) ? $request->approved : 'all');
        $today = Carbon::now();
        $appointments = Auth::user()
            ->company
            ->appointments()
            ->where(function ($query) use ($user){
                if (!$user->hasRole('owner')){
                    $query->where('user_id', $user->id);
                }
            })->with('staff:id,name')->with('service:id,name')           
            ->where(function ($query) use ($today, $time) {
                if ($time === 'next') {
                    $query->whereDate('start_time', '>=', $today);
                } elseif ($time === 'previous') {
                    $query->whereDate('start_time', '<=', $today);
                } else {

                }
            })
            ->where(function ($query) use ($approved) {
                if ($approved != 'all'){
                    if ($approved == 'approved') {
                        $query->where('approved', '=', 1);
                    } elseif ($approved == 'pending') {
                        $query->where('approved', '=', null);
                    } else {
    
                    }
                }
            })
            ->orderBy('start_time', 'desc')->paginate();

        return view('backoffice.appointments.index', compact('appointments', 'approved', 'time'));
    }
 
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Appointment $appointment)
    {
        $today = Carbon::now();
        $user = Auth::user();

        if (!$user->hasRole('owner') && $appointment->user_id != $user->id) {
            activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('NotAllowed');        

            return redirect(route('backoffice.appointments'))->with('error', trans('You can not access this appointment!'));        
        }

        $activities = Activity::forSubject($appointment)->get();
        
        activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('Viewed');        

        return view('backoffice.appointments.view', compact('appointment', 'today', 'activities'));
    }

    public function create()
    {
        $timezones = ['' => ' - - - - - - '];
        $tzlist = \DateTimeZone::listIdentifiers(\DateTimeZone::ALL);
        foreach($tzlist as $item){
            $timezones[$item] = $item;
        }        
        $selected = "Europe/London";

        $user = Auth::user();
        $serviceData = $user->company->services()->orderBy('created_at',  'desc')->get();
        $services[0] = " - - - - - ";
        foreach ($serviceData as $service) {
            $services[$service->id] = $service->name;
        }

        $company = $user->company;
        return view('backoffice.appointments.create', compact('timezones', 'selected', 'services', 'user', 'company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Appointment $appointment)
    {
        $serviceData = Auth::user()->company->services()->orderBy('created_at',  'desc')->get();
        $company = Auth::user()->company;
        $users = $appointment->service->team()->pluck('name', 'id');
        $services[0] = " - - - - - ";
        foreach ($serviceData as $service) {
            $services[$service->id] = $service->name;
        }

        $timezones = ['' => ' - - - - - - '];
        $tzlist = \DateTimeZone::listIdentifiers(\DateTimeZone::ALL);
        foreach($tzlist as $item){
            $timezones[$item] = $item;
        }        
        $selected = "Europe/London";

        return view('backoffice.appointments.edit', compact('appointment', 'services', 'users', 'timezones', 'selected', 'company'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function cancel(Appointment $appointment)
    {
        $user = Auth::user();

        if (!$user->hasRole('owner') && $appointment->user_id != $user->id) {
            activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('NotAllowed');        
            return redirect(route('backoffice.appointments'))->with('error', trans('You can not access this appointment!'));        
        }

        activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('Cancelled');

        $appointment->delete();
                
        Mail::to($appointment->customer_email)->queue(new AppointmentCanceled($appointment));
        return redirect(route('backoffice.appointments'))->with('success', trans('Appointment has been deleted!'));        
    }

    public function reminder(Appointment $appointment)
    {
        
        $user = Auth::user();
        if (!$user->hasRole('owner') && $appointment->user_id != $user->id) {
            activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('NotAllowed');        
            return redirect(route('backoffice.appointments'))->with('error', trans('You can not access this appointment!'));        
        }

        Mail::to($appointment->customer)->queue(new AppointmentReminder($appointment));
        return redirect(route('backoffice.appointments.view',  $appointment->id))->with('success', 'Appointment reminder email has been sent!');
    }

    public function approve(Appointment $appointment)
    {
        $user = Auth::user();
        if (!$user->hasRole('owner') && $appointment->user_id != $user->id) {
            activity()
            ->causedBy($user)
            ->performedOn($appointment)
            ->log('NotAllowed');        
            return redirect(route('backoffice.appointments'))->with('error', trans('You can not access this appointment!'));        
        }

        $appointment->approved = 1;
 
        if ($appointment->save()) {
            Mail::to($appointment->customer_email)
                    ->queue(new AppointmentApproved($appointment));
            return redirect(route('backoffice.appointments.view',  $appointment->id))->with('success', trans('Appointment has been approved!'));
        }
        return redirect(route('backoffice.appointments.view',  $appointment->id))->with('error', 'An error occured while verifiying this appointment!')->withInput();
    }
}

app/Http/Controllers/BackOffice/BaseController.php
<?php

namespace App\Http\Controllers\BackOffice;

use App\Models\User;
use Auth;
use Illuminate\Routing\Controller;

class BaseController extends Controller
{
    public function __construct()
    {
 
    }
}

resources/views/backoffice/services/create_edit.blade.php
@extends('layouts.panel')
@section('title')
{{ (isset($service)) ? 'Update a service' : 'Add a Service' }}
@parent
@stop
@section('css')
<link href="{{ mix('css/summernote-lite.css') }}" rel="stylesheet">
@stop
@section('content')
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header container-fluid">
                    <div class="row">
                        <div class="col-md-8">

                            <strong>{{ (isset($service)) ? 'Update a service' : 'Add a Service' }}</strong>
                        </div>
                        <div class="col-md-4 ">

                            <a class="btn btn-sm btn-primary float-right"
                                href="{{ route('backoffice.services.index') }}">
                                <i class="align-middle feather_small" data-feather="list"></i>
                                List Services</a>
                        </div>
                    </div>

                </div>
                <div class="card-body">
                    @include('backoffice.partials.notifications')

                    <div class="row">
                        <div class="col-sm-10 offset-sm-1">
                            <form autocomplete="off" role="form"
                                action="{{ (isset($service)) ? route('backoffice.services.update', $service->id ) : route('backoffice.services.store') }}"
                                method="POST">
                                <input type="hidden" name="_token" value="{{{ csrf_token() }}}" />

                                <div class="form-group row row {!! $errors->first('name', 'has-warning') !!}">
                                    <label for="name" class="col-sm-4 col-form-label">{{ trans('labels.name') }}
                                        {{ old('name')  }}</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" id="name" name="name" autocomplete="off"
                                            value="{{{ old('name', isset($service) ? $service->name : null) }}}">
                                        {!! $errors->first('name', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('description', 'has-warning') !!}">
                                    <label for="description"
                                        class="col-sm-4 col-form-label">{{ trans('labels.description') }}
                                        </label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" id="description"
                                            name="description">{{{ old('description', isset($service) ? $service->description : null) }}}</textarea>
                                        {!! $errors->first('descripton', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <div class="form-group row {!! $errors->first('duration', 'has-warning') !!}">
                                    <label for="duration" class="col-sm-4 col-form-label">{{ trans('labels.duration') }}
                                        {{ old('duration')  }}
                                        (mins*)</label>
                                    <div class="col-sm-8">
                                        {{ Form::select('duration', $durations, (isset($service) ? $service->duration : null), ['class'=>'form-control col-sm-3']) }}
                                        {!! $errors->first('duration', '<span class="help-inline">:message</span>') !!}
                                        {!! $errors->first('duration', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>
                                <div class="form-group row {!! $errors->first('price', 'has-warning') !!}">
                                    <label for="price" class="col-sm-4 col-form-label">{{ trans('labels.price') }}
                                        {{ old('price')  }}</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control col-sm-4" id="price" name="price"
                                            autocomplete="off"
                                            value="{{{ old('price', isset($service) ? $service->price : null) }}}">
                                        {!! $errors->first('price', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4 col-form-label">{{ trans('labels.team_member') }} </label>
                                    <div class="col-sm-8">
                                        @foreach($employees as $user)
                                        <div class="form-check" class="col-sm-4 col-form-label">
                                                @if(isset($service))
                                                <input type="checkbox" class="form-check-input" name="staff[]"
                                                    id="staff{{ $user->id }}" value="{{ $user->id }}"
                                                    {{ (in_array($user->id, $service->team->pluck('id')->toArray()) ? 'checked' : '') }} />
                                                @else
                                                <input type="checkbox" class="form-check-input" name="staff[]"
                                                    id="staff{{ $user->id }}" value="{{ $user->id }}" />
                                                @endif
                                                <label class="form-check-label" for="staff{{ $user->id }}">
                                                {{ $user->name }}</label>
                                        </div>

                                        @endforeach
                                        {!! $errors->first('staff[]', '<span class="help-block">:message</span>') !!}
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary pull-right">
                                    <i class="fa fa-save" aria-hidden="true"></i>
                                    {{ trans('labels.save') }}</button>

                            </form>


                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script src="{{ mix('js/summernote-lite.min.js') }}"></script>

<script>
$(document).ready(function() {
    $('#description').summernote({
        height: 100,
        toolbar: false,
        tabsize: 2
    });
});
</script>
@stop

resources/views/backoffice/services/index.blade.php
@extends('layouts.panel')
@section('title')
Services
@parent
@stop

@section('content')
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header container-fluid">
                    <div class="row">
                        <div class="col-md-8">
                            <strong>{{ (isset($service)) ? 'Update a service' : 'Add a Service' }}</strong>
                        </div>
                        <div class="col-md-4 ">
                            <a class="btn btn-sm btn-primary float-right"
                                href="{{ route('backoffice.services.create') }}">
                                <i class="align-middle feather_small" data-feather="plus"></i>
                                Add Service</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include('backoffice.partials.notifications')

                    @if($services->count() < 1) <div class="alert alert-warning">
                        Sorry there is no service!
                </div>
                @else
                <div class="table-responsive-sm">
                    <table class="table table-striped table-hover">
                        <thead class="thead-header">
                            <tr>
                                <th>Service</th>
                                <th>Duration</th>
                                <th>Fee</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($services as $service)
                            <tr>
                                <td>{{ $service->name }}</td>
                                <td>
                                    <i class="align-middle feather_small" data-feather="clock"></i>
                                    {{ $service->duration }} min.
                                </td>
                                <td>£{{ $service->service_price }}</td>
                                <td>

                                <a class="btn btn-sm btn-primary float-right ml-1"
                                        href="{{ route('backoffice.services.delete', $service->id) }}">
                                        <i class="align-middle feather_small" data-feather="delete"></i>
                                        Delete</a>

                                    <a class="btn btn-sm btn-primary float-right ml-1"
                                        href="{{ route('backoffice.services.edit', $service->id) }}">
                                        <i class="align-middle feather_small" data-feather="edit"></i>
                                        Edit</a>
                                    <a class="btn btn-sm btn-primary float-right ml-1"
                                        href="{{ route('backoffice.services.upload', $service->id) }}">
                                        <i class="fas fa-upload"></i> Upload</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
</div>
@endsection
@section('scripts')


@stop